In [10]:
import pandas as pd
import numpy as np

file_path = 'Data/cumulative_2025.10.04_14.49.10.csv'  

df = pd.read_csv(file_path, comment='#')

print("Header:", df.columns.tolist())
print("First 5 rows of data:", df.head())

# check for confirmed vs false positive in koi_pdisposition
print(df['koi_disposition'].value_counts())

Header: ['kepid', 'kepoi_name', 'kepler_name', 'koi_disposition', 'koi_pdisposition', 'koi_score', 'koi_fpflag_nt', 'koi_fpflag_ss', 'koi_fpflag_co', 'koi_fpflag_ec', 'koi_period', 'koi_period_err1', 'koi_period_err2', 'koi_time0bk', 'koi_time0bk_err1', 'koi_time0bk_err2', 'koi_impact', 'koi_impact_err1', 'koi_impact_err2', 'koi_duration', 'koi_duration_err1', 'koi_duration_err2', 'koi_depth', 'koi_depth_err1', 'koi_depth_err2', 'koi_prad', 'koi_prad_err1', 'koi_prad_err2', 'koi_teq', 'koi_teq_err1', 'koi_teq_err2', 'koi_insol', 'koi_insol_err1', 'koi_insol_err2', 'koi_model_snr', 'koi_tce_plnt_num', 'koi_tce_delivname', 'koi_steff', 'koi_steff_err1', 'koi_steff_err2', 'koi_slogg', 'koi_slogg_err1', 'koi_slogg_err2', 'koi_srad', 'koi_srad_err1', 'koi_srad_err2', 'ra', 'dec', 'koi_kepmag']
First 5 rows of data:       kepid kepoi_name   kepler_name koi_disposition koi_pdisposition  \
0  10797460  K00752.01  Kepler-227 b       CONFIRMED        CANDIDATE
1  10797460  K00752.02  Kepler-227 c       CONFIRMED        CANDIDATE
2  10811496  K00753.01           NaN       CANDIDATE        CANDIDATE
3  10848459  K00754.01           NaN  FALSE POSITIVE   FALSE POSITIVE
4  10854555  K00755.01  Kepler-664 b       CONFIRMED        CANDIDATE

   koi_score  koi_fpflag_nt  koi_fpflag_ss  koi_fpflag_co  koi_fpflag_ec  ...  \
0      1.000              0              0              0              0  ...
1      0.969              0              0              0              0  ...
2      0.000              0              0              0              0  ...
3      0.000              0              1              0              0  ...
4      1.000              0              0              0              0  ...

   koi_steff_err2  koi_slogg  koi_slogg_err1  koi_slogg_err2  koi_srad  \
0           -81.0      4.467           0.064          -0.096     0.927
1           -81.0      4.467           0.064          -0.096     0.927
2          -176.0      4.544           0.044          -0.176     0.868
3          -174.0      4.564           0.053          -0.168     0.791
4          -211.0      4.438           0.070          -0.210     1.046

   koi_srad_err1  koi_srad_err2         ra        dec  koi_kepmag
0          0.105         -0.061  291.93423  48.141651      15.347
1          0.105         -0.061  291.93423  48.141651      15.347
2          0.233         -0.078  297.00482  48.134129      15.436
3          0.201         -0.067  285.53461  48.285210      15.597
4          0.334         -0.133  288.75488  48.226200      15.509

[5 rows x 49 columns]
koi_disposition
FALSE POSITIVE    4839
CONFIRMED         2746
CANDIDATE         1979
Name: count, dtype: int64

In [11]:
print( df.columns.tolist())

['kepid', 'kepoi_name', 'kepler_name', 'koi_disposition', 'koi_pdisposition', 'koi_score', 'koi_fpflag_nt', 'koi_fpflag_ss', 'koi_fpflag_co', 'koi_fpflag_ec', 'koi_period', 'koi_period_err1', 'koi_period_err2', 'koi_time0bk', 'koi_time0bk_err1', 'koi_time0bk_err2', 'koi_impact', 'koi_impact_err1', 'koi_impact_err2', 'koi_duration', 'koi_duration_err1', 'koi_duration_err2', 'koi_depth', 'koi_depth_err1', 'koi_depth_err2', 'koi_prad', 'koi_prad_err1', 'koi_prad_err2', 'koi_teq', 'koi_teq_err1', 'koi_teq_err2', 'koi_insol', 'koi_insol_err1', 'koi_insol_err2', 'koi_model_snr', 'koi_tce_plnt_num', 'koi_tce_delivname', 'koi_steff', 'koi_steff_err1', 'koi_steff_err2', 'koi_slogg', 'koi_slogg_err1', 'koi_slogg_err2', 'koi_srad', 'koi_srad_err1', 'koi_srad_err2', 'ra', 'dec', 'koi_kepmag']

In [12]:
# keep only kepid, koi_disposition, koi_period, koi_time0bk, koi_impact, koi_duration, koi_depth, koi_prad, koi_teq, koi_insol, koi_model_snr, koi_steff, koi_slogg, koi_srad, ra, dec, koi_kepmag
df_columns_of_interest = ['kepid', 'koi_disposition', 'koi_period', 'koi_time0bk', 'koi_impact', 'koi_duration', 'koi_depth', 'koi_prad', 'koi_teq', 'koi_insol', 'koi_model_snr', 'koi_steff', 'koi_slogg', 'koi_srad', 'ra', 'dec', 'koi_kepmag']

df_filtered = df[df_columns_of_interest]

df_filtered.head()

,kepid,koi_disposition,koi_period,koi_time0bk,koi_impact,koi_duration,koi_depth,koi_prad,koi_teq,koi_insol,koi_model_snr,koi_steff,koi_slogg,koi_srad,ra,dec,koi_kepmag
0,10797460,CONFIRMED,9.488036,170.538750,0.146,2.95750,615.8,2.26,793.0,93.59,35.8,5455.0,4.467,0.927,291.93423,48.141651,15.347
1,10797460,CONFIRMED,54.418383,162.513840,0.586,4.50700,874.8,2.83,443.0,9.11,25.8,5455.0,4.467,0.927,291.93423,48.141651,15.347
2,10811496,CANDIDATE,19.899140,175.850252,0.969,1.78220,10829.0,14.60,638.0,39.30,76.3,5853.0,4.544,0.868,297.00482,48.134129,15.436
3,10848459,FALSE POSITIVE,1.736952,170.307565,1.276,2.40641,8079.2,33.46,1395.0,891.96,505.6,5805.0,4.564,0.791,285.53461,48.285210,15.597
4,10854555,CONFIRMED,2.525592,171.595550,0.701,1.65450,603.3,2.75,1406.0,926.16,40.9,6031.0,4.438,1.046,288.75488,48.226200,15.509

In [13]:
# check for null values and empty columns
print("Null values in each column:\n", df_filtered.isnull().sum())

# show confirmed vs false positive
print(df_filtered['koi_disposition'].value_counts())

# remove rows with null values
df_filtered_dropped_null = df_filtered.dropna()

# show the size of the dataframe after removing null values
print("\n DataFrame size after removing null values:", df_filtered_dropped_null.shape)
print(df_filtered_dropped_null['koi_disposition'].value_counts())

Null values in each column:
 kepid                0
koi_disposition      0
koi_period           0
koi_time0bk          0
koi_impact         363
koi_duration         0
koi_depth          363
koi_prad           363
koi_teq            363
koi_insol          321
koi_model_snr      363
koi_steff          363
koi_slogg          363
koi_srad           363
ra                   0
dec                  0
koi_kepmag           1
dtype: int64
koi_disposition
FALSE POSITIVE    4839
CONFIRMED         2746
CANDIDATE         1979
Name: count, dtype: int64

 DataFrame size after removing null values: (9200, 17)
koi_disposition
FALSE POSITIVE    4581
CONFIRMED         2744
CANDIDATE         1875
Name: count, dtype: int64

In [18]:
# add column for binary classification: 1 for CONFIRMED, 0 for FALSE POSITIVE using loc
df_filtered_dropped_null.loc[df_filtered_dropped_null['koi_disposition'] == 'CONFIRMED', 'label'] = 1
df_filtered_dropped_null.loc[df_filtered_dropped_null['koi_disposition'] == 'FALSE POSITIVE', 'label'] = 0

# drop koi_disposition and kepid column keep only label column
df_binary_labeled = df_filtered_dropped_null.drop(columns=['koi_disposition', 'kepid'], axis=1)

df_binary_labeled.head()

,koi_period,koi_time0bk,koi_impact,koi_duration,koi_depth,koi_prad,koi_teq,koi_insol,koi_model_snr,koi_steff,koi_slogg,koi_srad,ra,dec,koi_kepmag,label
0,9.488036,170.538750,0.146,2.95750,615.8,2.26,793.0,93.59,35.8,5455.0,4.467,0.927,291.93423,48.141651,15.347,1.0
1,54.418383,162.513840,0.586,4.50700,874.8,2.83,443.0,9.11,25.8,5455.0,4.467,0.927,291.93423,48.141651,15.347,1.0
2,19.899140,175.850252,0.969,1.78220,10829.0,14.60,638.0,39.30,76.3,5853.0,4.544,0.868,297.00482,48.134129,15.436,NaN
3,1.736952,170.307565,1.276,2.40641,8079.2,33.46,1395.0,891.96,505.6,5805.0,4.564,0.791,285.53461,48.285210,15.597,0.0
4,2.525592,171.595550,0.701,1.65450,603.3,2.75,1406.0,926.16,40.9,6031.0,4.438,1.046,288.75488,48.226200,15.509,1.0

In [19]:
# Extract candidate rows (where label is NaN)
df_candidates = df_binary_labeled[df_binary_labeled['label'].isna()].drop(columns=['label'])

# Save candidates to a CSV file for demo predictions
df_candidates.to_csv('Data/candidate_rows.csv', index=False)

# Keep only rows with valid labels (non-null)
df_binary_labeled = df_binary_labeled[df_binary_labeled['label'].notna()]

print("Filtered DataFrame size:", df_binary_labeled.shape)

df_binary_labeled.head()

Filtered DataFrame size: (7325, 16)

,koi_period,koi_time0bk,koi_impact,koi_duration,koi_depth,koi_prad,koi_teq,koi_insol,koi_model_snr,koi_steff,koi_slogg,koi_srad,ra,dec,koi_kepmag,label
0,9.488036,170.538750,0.146,2.95750,615.8,2.26,793.0,93.59,35.8,5455.0,4.467,0.927,291.93423,48.141651,15.347,1.0
1,54.418383,162.513840,0.586,4.50700,874.8,2.83,443.0,9.11,25.8,5455.0,4.467,0.927,291.93423,48.141651,15.347,1.0
3,1.736952,170.307565,1.276,2.40641,8079.2,33.46,1395.0,891.96,505.6,5805.0,4.564,0.791,285.53461,48.285210,15.597,0.0
4,2.525592,171.595550,0.701,1.65450,603.3,2.75,1406.0,926.16,40.9,6031.0,4.438,1.046,288.75488,48.226200,15.509,1.0
5,11.094321,171.201160,0.538,4.59450,1517.5,3.90,835.0,114.81,66.5,6046.0,4.486,0.972,296.28613,48.224670,15.714,1.0

In [20]:
# save as new csv file
df_binary_labeled.to_csv('Data/preprocessed_exoplanet_data.csv', index=False)